server:
  port: 8083

spring:
  application:
    name: user-service
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: shopsphere
      username: root
      password: root
  data:
    redis:
      host: redis
      port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.shopsphere: DEBUG
    org.springframework: INFO 