server:
  port: 8081

spring:
  application:
    name: product-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopsphere
      authentication-database: admin
      username: root
      password: root
  data:
    elasticsearch:
      uris: http://localhost:9200
      username: elastic
      password: changeme
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha 